FROM debian:11 as build
RUN apt-get -y update && apt-get -y install curl && curl -sL https://deb.nodesource.com/setup_18.x | bash - && apt-get install nodejs
COPY ./front-end /src
WORKDIR /src
RUN npm install && npm run build

FROM nginx:alpine

COPY --from=build /src/dist /usr/src/fe/
COPY fe.conf etc/nginx/conf.d/default.conf
COPY start.sh /start.sh
RUN chmod +x /start.sh

EXPOSE 80

CMD ["/start.sh"]
